#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka
#
#spring:
#  cloud:
#    config:
#      override-system-properties: false
