spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ayg.ecommerce.kafka.OrderConfirmation, paymentConfirmation:com.ayg.ecommerce.notification.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail.smtp.trust : '*'
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000

servet:
  port : 8040


